### ISSUE TITLE
Extension does not seem to launch

### ISSUE THREAD

**Issue by lbrndnr** [mmshivesh/Python-Nova.novaextension#10]
Hi Shivesh,

I tried the extension but nothing seems to happening. Here's a quick summary of my setup
- running Big Sur
- set my `pyls` path to `/Users/Laurin/Library/Python/3.8/bin/pyls`. This is where it was installed using `pip`

The following is printed to the extension console, even when typing in a python file.
```
Python[18:12:08.086000] pyls.executable: /Users/Laurin/Library/Python/3.8/bin/pyls 
Python[18:12:08.087000] pyls.enableLogging: false
```

Is there any info I can help you with resolving this issue? :) Thanks either way for your extension, would be super useful!

**Comment by Teaguen** [comment]
I second this, can't seem to get it to do anything no matter how hard I try.

**Comment by x1klim** [comment]
Same thing over here

**Comment by mmshivesh** [comment]
Okay that's super weird. Did this start after the latest Nova update?

**Comment by x1klim** [comment]
> Okay that's super weird. Did this start after the latest Nova update?

I remember trying to install your extension last year and getting the same results — no visible signs of life, so I don't think that it is the latest update that's causing this. (also sorry that I didn't report it back then)

I'm suspicious that it might be incompatible with M1 chip, but I'm not sure if @lbrndnr or @Teaguen are also experiencing this on M1 machines.
