### ISSUE TITLE
PydocStyle ignore errors and warnings not loading correctly

### ISSUE THREAD

**Issue by mattie-dev** [mmshivesh/Python-Nova.novaextension#17]
In order to get the errors or warnings to be ignored, you need to turn off and on the extension every time you open a project in nova.  The only one I've tried is E501, which is for line length warnings, and every time a project is opened, those warnings come back until I enable and disable the extension.

Edit - Sorry for the inconvenience I just realized this issue is already posted: https://github.com/mmshivesh/Python-Nova.novaextension/issues/8#issue-742905692

**Comment by guillaumealgis** [comment]
Fixed in https://github.com/mmshivesh/Python-Nova.novaextension/pull/19

Maybe also related to https://github.com/mmshivesh/Python-Nova.novaextension/pull/18
