### ISSUE TITLE
Python process using 100% CPU?

### ISSUE THREAD

**Issue by Gugu7264** [mmshivesh/Python-Nova.novaextension#21]
I don't have a screenshot of the activity monitor at this time, but it seems that when I start the extension, a Python process is created for each Nova window, and this Python process is using 100% CPU (I have 8 cores, so each process = 1 full core).
Is that a unique issue to me or are other people encountering this?

**Comment by jbergstroem** [comment]
Same here; the instant I turn the extension on, it consumes all my cpu.

**Comment by marriotb** [comment]
It was doing the same for me. Not all the time: doesn't do it if only the Launcher window is open, but if a file window is open it did. 

This was running Nova 8.3 in Big Sur 11.6.2 & Python 3.10.1 on Apple Silicon.

Upgrading to Nova 8.4 stopped this issue, but now I have another - pyls_jsonrpc.endpoint dies and leaves me with nothing. I'll raise that one separately, but it's looking like this plug-in isn't worth the effort.

**Comment by mmshivesh** [comment]
@jbergstroem @Gugu7264 Did @marriotb 's solution work to fix this, i.e. Updating to Nova 8.4 (or Nova 9) and Python 3.10.2?

**Comment by jbergstroem** [comment]
I tested with `Nova 9` and `Python 3.9.10` via Homebrew. Seems fixed.

**Comment by mmshivesh** [comment]
Thanks!
